name: 'Autoprefix CSS'
description: 'Uses Autoprefixer to prefix your CSS files for the configured browsers.'
author: 'Konrad Rej'
inputs:
  source_dir:
    description: 'Source directory containing CSS files'
    required: false
    default: 'css'
  destination_dir:
    description: 'Destination directory for prefixed CSS files'
    required: false
    default: 'css/prefixed'
  file_prefix:
    description: 'Filename prefix for prefixed files'
    required: false
    default: ''
  file_suffix:
    description: 'Filename suffix for prefixed files'
    required: false
    default: ''

    # Config value for configuring the browsers

runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'file-plus'
  color: 'orange'